version: '3'

services:
  php-laravel:
    image: web-app-bootcamp/php-laravel
    build: ./api/php-laravel
    ports:
      - "8000:80"
    volumes:
      - ./api/php-laravel/bootcamp:/var/www/bootcamp:cached
    depends_on:
      - mysql
    networks: 
      - database

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    networks: 
      - database

  migrate:
    image: migrate/migrate:v4.6.2
    volumes:
    - ./migration:/migrations
    networks: 
      - database


volumes:
  mysql-data:

networks:
  database:
