version: '3'

services:
  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-laravel
      - csharp-asp-dotnet
      - ruby-on-rails

  php-laravel:
    image: web-app-bootcamp/php-laravel
    build: ./api/php-laravel
    expose:
      - 9000
    volumes:
      - ./api/php-laravel/bootcamp:/var/www/bootcamp:cached
    depends_on:
      - mysql

  csharp-asp-dotnet:
    image: web-app-bootcamp/csharp-asp-dotnet
    build: ./api/csharp-asp-dotnet
    expose:
      - 5000
    volumes:
      - ./api/csharp-asp-dotnet/bootcamp:/app/bootcamp:cached
    depends_on:
      - mysql

  ruby-on-rails:
    image: web-app-bootcamp/ruby-on-rails
    build: ./api/ruby-on-rails
    expose:
      - 3000
    volumes:
      - ./api/ruby-on-rails/bootcamp:/var/www/bootcamp:cached
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  migrate:
    image: migrate/migrate:v4.6.2
    volumes:
    - ./migration:/migrations

volumes:
  mysql-data:

