FROM php:7.4.0RC3-cli-alpine3.10

LABEL mantainer=MasanoriIwakura

# RUN apk --no-cache add wget composer && \
#     wget https://github.com/spiral/roadrunner/releases/download/v1.4.8/roadrunner-1.4.8-linux-amd64.tar.gz && \
#     tar -xvzf roadrunner-1.4.8-linux-amd64.tar.gz && \
#     mv roadrunner-1.4.8-linux-amd64 roadrunner && \
#     rm -f roadrunner-1.4.8-linux-amd64.tar.gz && \
#     apk del wget
